name: "Build & Test"

on:
  push:
    branches:
      - master
      - branch-DDS-3.*
      - gh_wf_*
    paths:
      - '**'
      # Don't run this workflow if the only files that changed are the
      # following. Make sure this is the same as the "pull_request.paths" list.
      - '!AUTHORS'
      - '!PROBLEM-REPORT-FORM'
      - '!LICENSE'
      - '!Dockerfile**'
      - '!.dockerignore'
      - '!.mailmap'
      - '!.github/workflows/lint.yml'
      - '!etc/**'
      - '!docs/**'
      - '!hooks/**'
      - '!tools/scripts/**'
      - '!**.md'
      - '!**.rst'
      - '!**/.gitignore'
      - '!**/.lint_config'
      - '!**/README*'
  pull_request:
    branches:
      - master
      - branch-DDS-3.*
    paths:
      - '**'
      # Don't run this workflow if the only files that changed are the
      # following. Make sure this is the same as the "push.paths" list.
      - '!AUTHORS'
      - '!PROBLEM-REPORT-FORM'
      - '!LICENSE'
      - '!Dockerfile**'
      - '!.dockerignore'
      - '!.mailmap'
      - '!.github/workflows/lint.yml'
      - '!etc/**'
      - '!docs/**'
      - '!hooks/**'
      - '!tools/scripts/**'
      - '!**.md'
      - '!**.rst'
      - '!**/.gitignore'
      - '!**/.lint_config'
      - '!**/README*'

env:
  TRIGGERING_COMMIT: ${{ github.event.pull_request.head.sha || github.sha }}

jobs:

  wait_cancel_previous:

    runs-on: ubuntu-20.04

    steps:
    - uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
        owner: ${{ github.repository_owner }}
        repo: OpenDDS
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow_file_name: cancel_previous_runs.yml
        ref: ${{ env.TRIGGERING_COMMIT }}
        trigger_workflow: false

  repo_u20_p1:

    runs-on: ubuntu-20.04

    needs: wait_cancel_previous

    steps:
    - name: checkout OpenDDS
      uses: actions/checkout@v2.3.4
      with:
        path: OpenDDS
        submodules: true
    - name: checkout ACE_TAO
      uses: actions/checkout@v2.3.4
      with:
        repository: DOCGroup/ACE_TAO
        ref: ace6tao2
        path: OpenDDS/ACE_TAO
    - name: get ACE_TAO commit
      shell: bash
      run: |
        cd OpenDDS/ACE_TAO
        export ACE_COMMIT=$(git rev-parse HEAD)
        echo "ACE_COMMIT=$ACE_COMMIT" >> $GITHUB_ENV
    - name: install xerces
      run: sudo apt-get -y install libxerces-c-dev
    - name: checkout MPC
      uses: actions/checkout@v2.3.4
      with:
        repository: DOCGroup/MPC
        path: MPC
    - name: configure OpenDDS
      run: |
        cd OpenDDS
        ./configure --rapidjson --tests --std=c++11 --security --ipv6 --no-built-in-topics --ace=$GITHUB_WORKSPACE/OpenDDS/ACE_TAO/ACE --mpc=$GITHUB_WORKSPACE/MPC
    - name: Build Messenger Tests
      run: |
        cd OpenDDS
        . setenv.sh
        make -j4 DCPSInfoRepo_Main DDS_Messenger_Publisher DDS_Messenger_Subscriber
    - name: Get IP Info
      run: |
        ip addr
    - name: Run Host For Hostnames
      run: |
        hostname --all-fqdns | sed 's/ /\n/g' | sort -u | grep "[^ ]" | xargs -I {} /usr/bin/host {}
    - name: Run Host For IP Addresses
      run: |
        echo "Here are some ip addresses:"
        ip addr | grep global | grep -v temp | grep -v tmp | sed 's/ [ ]*/ /g' | cut -d ' ' -f 3 | cut -d '/' -f 1
        echo "And here they are, passed to host:"
        ip addr | grep global | grep -v temp | grep -v tmp | sed 's/ [ ]*/ /g' | cut -d ' ' -f 3 | cut -d '/' -f 1 | xargs -I {} host {}
    - name: Run Messenger Tests - Round 1
      run: |
        cd OpenDDS
        . setenv.sh
        cd tests/DCPS/Messenger
        ./run_test.pl
    - name: Run Messenger Tests - Round 2
      if: ${{ always() }}
      run: |
        cd OpenDDS
        . setenv.sh
        cd tests/DCPS/Messenger
        ./run_test.pl
    - name: Run Messenger Tests - Round 3
      if: ${{ always() }}
      run: |
        cd OpenDDS
        . setenv.sh
        cd tests/DCPS/Messenger
        ./run_test.pl

